---
- include_role:
    name: terraplate/component
  tags: alb

- name: Create an ALB
  include_role:
    name: terraplate/aws/ec2/alb
  vars:
    tfvars:
      tags:
        Name: testing
    external_tfvars:
      subnets:
        - { provider: vpc, name: vpc_subnet_public_subnet_id }
        - { provider: vpc, name: vpc_subnet_public_2_subnet_id }
      security_groups:
        - { provider: sg, name: vpc_sg_elb_rails_security_group_id }
  tags: alb
